In [1]:
import pandas as pd
import re

## Does Economic Inequality Predict Happiness? 
#### A Data‑Driven Exploration of Global Well‑Being

### Introduction
Happiness is something everyone cares about, yet it often feels mysterious. Some countries seem to consistently report higher life satisfaction, while others struggle year after year. It’s easy to assume that wealth alone explains the difference, but the story is rarely that simple. Happiness is often treated as something personal and subjective, yet it is measured every year on a global scale. Countries are ranked, compared, and analyzed based on how satisfied their citizens feel with their lives. In recent years, more attention has been drawn to the idea that economic inequality — the gap between the richest and poorest people — might play a role in how happy a society feels. The idea that large gaps between the rich and the poor continues to be discussed as one of the major forces shaping social well‑being. 

The idea sounds intuitive. When opportunities are unevenly distributed, trust can be weakened, stress can rise, and people may feel that life is less fair. But is this actually reflected in the data? Or is inequality just one of many factors that shape well‑being?

**Does economic inequality predict how happy a country is — and how does it compare to other development factors?**

Three large and respected sources of real‑world data are used in this project. The World Happiness Report (2005–2024), The World Bank’s Gini Index dataset, and the World Bank’s World Development Indicators (WDI) datasets are brought together in attempt to give an answer to this simple but meaningful question.
  
The goal of this project is not only to look for statistical relationships, but also to tell a clear and accessible story about what the data suggests. Patterns across regions will be examined, trends over time will be visualized, and several hypotheses will be tested to see whether inequality truly stands out as a key factor in national well‑being.

In the end, the hope is that the findings will offer a clearer picture of how fairness, opportunity, and economic balance might shape the emotional landscape of societies around the world — and why this matters for all of us.

### Problem Formulation & Methodology
Several guiding questions shape this investigation:

- Do countries with higher inequality tend to report lower happiness?

- Are certain regions more affected by inequality than others?

- Does economic prosperity or development change the relationship between inequality and happiness?

The project aims to translate a broad social question into a structured, data‑driven analysis. The hope is that the findings will offer a clearer understanding of how fairness, opportunity, and economic conditions might influence the emotional well‑being of entire societies.

The analysis begins with data cleaning and preparation. Country names are standardized, years are aligned, and only observations with valid values for the key variables are retained.

Once the datasets are merged, exploratory data analysis (EDA) is conducted to understand distributions, identify regional patterns, and visualize trends over time. Correlation analysis is used to examine how happiness relates to inequality and development indicators. Group comparisons help reveal whether certain regions experience stronger inequality–happiness relationships than others.

To test the guiding hypotheses, statistical methods such as regression analysis are applied. These models allow the relationship between inequality and happiness to be examined both on its own and while controlling for development factors like GDP, education, health, and inflation. Temporal comparisons are also made to assess whether the strength of these relationships changes across years.

### Hypotheses
To explore how inequality and happiness might be connected, three core hypotheses are formed. These are designed to guide the analysis in a clear and manageable way, while still capturing the most important aspects of the topic.

##### Hypothesis 1 — Inequality and Happiness
*This hypothesis examines whether inequality and well‑being move in opposite directions across countries.* 

**H0**:  There is no relationship between the Gini Index and the Happiness (Ladder) Score.\
**H1**:  Higher Gini Index values are associated with lower Happiness Scores.

##### Hypothesis 2 — Regional Differences
*This allows the analysis to explore whether some regions are more sensitive to inequality than others.* 

**H0**:  The relationship between inequality and happiness does not differ across world regions.\
**H1**:  The relationship between inequality and happiness differs across world regions.

##### Hypothesis 3 — The Role of Development Factors
*This hypothesis tests whether inequality matters more or less depending on a country’s economic and social conditions.* 

**H0**:  Development indicators (GDP, education, health expenditure, inflation, urbanization) do not influence the relationship between inequality and happiness.\
**H1**:  Development indicators influence the relationship between inequality and happiness.

### Data Description & Data Collection
This project uses three complementary datasets that together provide a broad view of national well‑being, economic inequality, and development conditions. Each dataset contributes a different dimension of information, allowing the analysis to explore how happiness relates to both inequality and wider economic factors.
The data collection process involves obtaining the three datasets from publicly available and reputable sources, followed by preparing them for analysis through cleaning, filtering, and merging.

A sample of each dataset is displayed below for illustrative purposes.

#### 1. World Happiness Report (2005–2024) 
The World Happiness Report (WHR) provides annual measurements of subjective well‑being for countries around the world. The main variable used in this project is the *Ladder Score*, which reflects how people rate their overall life satisfaction on a scale from 0 to 10. Additional WHR indicators such as GDP per capita, social support, life expectancy, freedom, and perceptions of corruption are included as contextual variables. The dataset covers the years 2005–2024, although availability varies by country.
The WHR dataset is downloaded from Kaggle, where it is provided in a clean, tabular format. The file includes yearly happiness scores and supporting indicators. After loading the data, column names are standardized, and only the variables relevant to the analysis are retained. The dataset is then filtered to include only country‑level observations.

In [2]:
whr = pd.read_csv(
    "Data/raw/World-happiness-report-updated_2024.csv",
    encoding="latin1",
)
whr.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.350,0.451,50.5,0.718,0.164,0.882,0.414,0.258
1,Afghanistan,2009,4.402,7.509,0.552,50.8,0.679,0.187,0.850,0.481,0.237
2,Afghanistan,2010,4.758,7.614,0.539,51.1,0.600,0.118,0.707,0.517,0.275
3,Afghanistan,2011,3.832,7.581,0.521,51.4,0.496,0.160,0.731,0.480,0.267
4,Afghanistan,2012,3.783,7.661,0.521,51.7,0.531,0.234,0.776,0.614,0.268

#### 2. Gini Index Dataset (World Bank)
The *Gini Index* is one of the most widely used measures of income inequality. It ranges from 0 (perfect equality) to 100 (maximum inequality). The version used in this project comes from a cleaned Kaggle compilation based on World Bank data, providing a long‑format structure with country‑year observations. This dataset offers broad coverage across regions and decades, making it suitable for comparing inequality levels over time.

The *Gini Index* data is sourced from a Kaggle dataset that compiles World Bank inequality statistics into a long‑format structure. This version is chosen because it is already cleaned, consistently formatted, and easier to merge with other datasets than the raw World Bank files. After loading the data, country names and years are checked for consistency with the WHR dataset.

In [3]:
gini = pd.read_csv("Data/raw/gini_by_country.csv")
gini.head()

  country_code country_name  year  value
0          AGO       Angola  2000   52.0
1          AGO       Angola  2008   42.7
2          AGO       Angola  2018   51.3
3          ALB      Albania  1996   27.0
4          ALB      Albania  2002   31.7

#### 3. World Development Indicators (WDI)
To capture broader economic and social conditions, several indicators are taken from the World Bank’s World Development Indicators dataset. These include:

- GDP (current US$) — a measure of economic size
- Government expenditure on education (% of GDP) — a proxy for investment in human capital
- Government health expenditure (% of GDP) — reflecting national health investment
- Inflation (annual %) — capturing macroeconomic stability
- Urban population (%) — calculated from population and rural population values

In [4]:
wdi_indicators = pd.read_csv("Data/raw/wdi-indicators-5.csv")
wdi_indicators

,Indicator,Column in Dataset,How It Relates to the Analysis
0,GDP (current US$),GDP_current_US,Measures the size of a country’s economy. Used...
1,Education Expenditure (% of GDP),government_expenditure_on_education%,Captures national investment in human capital....
2,Health Expenditure (% of GDP),government_health_expenditure%,Reflects investment in public health systems. ...
3,Inflation (annual %),inflation_annual%,Indicates macroeconomic stability. High inflat...
4,Urban Population (%),urban_population% (computed from population an...,Represents the share of people living in urban...

These variables provide essential context for understanding how development conditions may influence or moderate the relationship between inequality and happiness.
Together, the three datasets form a unified panel of country‑year observations that combine subjective well‑being, inequality, and development indicators into a single analytical framework.
The WDI dataset is also obtained from Kaggle, where it is provided as a consolidated table containing selected economic and social indicators. From this dataset, five variables are extracted: GDP, education expenditure, health expenditure, inflation, and population measures. Urban population share is computed directly from the population and rural population columns. The dataset is then filtered to keep only the columns needed for the analysis.

In [5]:
wdi = pd.read_csv(
    "Data/raw/world_bank_development_indicators.csv",
    encoding="latin1",
)
wdi.head()

,country,date,agricultural_land%,forest_land%,land_area,avg_precipitation,trade_in_services%,control_of_corruption_estimate,control_of_corruption_std,access_to_electricity%,...,multidimensional_poverty_headcount_ratio%,gini_index,birth_rate,death_rate,life_expectancy_at_birth,population,rural_population,voice_and_accountability_estimate,voice_and_accountability_std,intentional_homicides
0,Afghanistan,1960-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,50.340,31.921,32.535,8622466.0,7898093.0,NaN,NaN,NaN
1,Afghanistan,1961-01-01,57.878356,NaN,652230.0,327.0,NaN,NaN,NaN,NaN,...,NaN,NaN,50.443,31.349,33.068,8790140.0,8026804.0,NaN,NaN,NaN
2,Afghanistan,1962-01-01,57.955016,NaN,652230.0,327.0,NaN,NaN,NaN,NaN,...,NaN,NaN,50.570,30.845,33.547,8969047.0,8163985.0,NaN,NaN,NaN
3,Afghanistan,1963-01-01,58.031676,NaN,652230.0,327.0,NaN,NaN,NaN,NaN,...,NaN,NaN,50.703,30.359,34.016,9157465.0,8308019.0,NaN,NaN,NaN
4,Afghanistan,1964-01-01,58.116002,NaN,652230.0,327.0,NaN,NaN,NaN,NaN,...,NaN,NaN,50.831,29.867,34.494,9355514.0,8458694.0,NaN,NaN,NaN

#### Merging the Datasets
Once each dataset is cleaned and standardized, they are merged using country and year as the common keys. Country names are harmonized across sources, and years are converted to a consistent numeric format. Observations with missing values in the key variables are handled appropriately to ensure a reliable final dataset.

The result is a unified analytical dataset that brings together happiness, inequality, and development indicators for a wide range of countries and years, forming the foundation for the exploratory and statistical analysis that follows.

### Data Cleaning & Preparation
This section describes the cleaning and preparation steps applied to each dataset before merging them into a unified analytical table. The goal is to ensure consistent country names, aligned years, and complete values for the variables used in the analysis.

#### 1. World Happiness Report (WHR)
##### Initial inspection of the basic structure.

In [6]:
whr.shape # return number of rows and columns

(2363, 11)

In [7]:
whr.info() # return column types and non-null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2363 entries, 0 to 2362
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country name                      2363 non-null   object
 1   year                              2363 non-null   int64
 2   Life Ladder                       2363 non-null   float64
 3   Log GDP per capita                2335 non-null   float64
 4   Social support                    2350 non-null   float64
 5   Healthy life expectancy at birth  2300 non-null   float64
 6   Freedom to make life choices      2327 non-null   float64
 7   Generosity                        2282 non-null   float64
 8   Perceptions of corruption         2238 non-null   float64
 9   Positive affect                   2339 non-null   float64
 10  Negative affect                   2347 non-null   float64
dtypes: float64(9), int64(1), object(1)
memory usage: 203.2+ KB

In [8]:
whr.columns # return list of column names

Index(['Country name', 'year', 'Life Ladder', 'Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Positive affect', 'Negative affect'],
      dtype='object')

In [9]:
whr.isna().sum() # check for missing values

Country name                          0
year                                  0
Life Ladder                           0
Log GDP per capita                   28
Social support                       13
Healthy life expectancy at birth     63
Freedom to make life choices         36
Generosity                           81
Perceptions of corruption           125
Positive affect                      24
Negative affect                      16
dtype: int64

##### Clean and normalize column names

In [10]:
def clean_col(col):
    col = re.sub(r'[^\x20-\x7E]+', '', col)  # remove all non-printable characters
    col = col.strip().replace("  ", " ")  # normalize spaces
    return col

In [11]:
whr.columns = [clean_col(c) for c in whr.columns]

for col in whr.columns:
    print(repr(col))

'Country name'
'year'
'Life Ladder'
'Log GDP per capita'
'Social support'
'Healthy life expectancy at birth'
'Freedom to make life choices'
'Generosity'
'Perceptions of corruption'
'Positive affect'
'Negative affect'

##### Rename and select key variables needed for analysis

In [12]:
whr = whr.rename(columns={
    "Life Ladder": "Happiness",
    "Log GDP per capita": "GDP_per_capita",
    "Healthy life expectancy at birth": "Life_expectancy",         # rename important variables
    "Freedom to make life choices": "Freedom",
    "Perceptions of corruption": "Corruption"
})

In [13]:
whr_use = whr[[
    "Country name",
    "year",
    "Happiness",
    "GDP_per_capita",
    "Social support",         # keep important variables
    "Life_expectancy",
    "Freedom",
    "Corruption"
]].copy()

##### Finalize column names for merging

In [14]:
whr_use = whr_use.rename(columns={
    "Country name": "Country",
    "Social support": "Social_support"
})

##### Now WHR subset has standard names:
Country | year | Happiness | GDP_per_capita | Social_support | Life_expectancy | Freedom | Corruption

In [15]:
whr_use["year"] = whr_use["year"].astype(int) # make sure year is numeric and consistent for merging

##### Handle and check missing values in key variables

In [16]:
whr_use = whr_use.dropna(subset=["Happiness"]) # remove rows where the main outcome "Happiness" is missing

In [17]:
whr_use.isna().sum() # check for missing values

Country              0
year                 0
Happiness            0
GDP_per_capita      28
Social_support      13
Life_expectancy     63
Freedom             36
Corruption         125
dtype: int64

##### Check cleaned WHR dataset

In [18]:
whr_use.shape
whr_use.info()
whr_use.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2363 entries, 0 to 2362
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country          2363 non-null   object
 1   year             2363 non-null   int64
 2   Happiness        2363 non-null   float64
 3   GDP_per_capita   2335 non-null   float64
 4   Social_support   2350 non-null   float64
 5   Life_expectancy  2300 non-null   float64
 6   Freedom          2327 non-null   float64
 7   Corruption       2238 non-null   float64
dtypes: float64(6), int64(1), object(1)
memory usage: 147.8+ KB

,Country,year,Happiness,GDP_per_capita,Social_support,Life_expectancy,Freedom,Corruption
0,Afghanistan,2008,3.724,7.350,0.451,50.5,0.718,0.882
1,Afghanistan,2009,4.402,7.509,0.552,50.8,0.679,0.850
2,Afghanistan,2010,4.758,7.614,0.539,51.1,0.600,0.707
3,Afghanistan,2011,3.832,7.581,0.521,51.4,0.496,0.731
4,Afghanistan,2012,3.783,7.661,0.521,51.7,0.531,0.776

#### 2. Gini Index
##### Initial inspection of the basic structure

In [19]:
gini.shape # return number of rows and columns

(1896, 4)

In [20]:
gini.info() # return column types and non-null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1896 entries, 0 to 1895
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country_code  1896 non-null   object
 1   country_name  1896 non-null   object
 2   year          1896 non-null   int64
 3   value         1896 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 59.4+ KB

In [21]:
gini.columns # return list of column names

Index(['country_code', 'country_name', 'year', 'value'], dtype='object')

In [22]:
gini.isna().sum() # check for missing values

country_code    0
country_name    0
year            0
value           0
dtype: int64

##### Clean and normalize column names

In [23]:
def clean_col(col):
    col = re.sub(r'[^\x20-\x7E]+', '', col)  # remove non-printable chars
    col = col.strip().replace("  ", " ")     # normalize spaces
    return col

In [24]:
gini.columns = [clean_col(c) for c in gini.columns]

for col in gini.columns:                    # give you the exact, correct rename mapping
    print(repr(col))

'country_code'
'country_name'
'year'
'value'

##### Standardize and rename key column names

In [25]:
gini = gini.rename(columns={
    "Country": "Country",
    "Country Name": "Country",      # if present instead
    "Year": "year",
    "Gini index": "Gini",
    "GINI index": "Gini"           # rename columns to match WHR and WDI
})

In [26]:
gini = gini.rename(columns={
    "country_name": "Country",
    "value": "Gini"               # rename columns to match WHR and WDI
})

##### Now Gini Index subset has standard names:
country_code | Country | year | Gini

In [27]:
gini["year"] = gini["year"].astype(int)  # make sure year is intiger and consistent for merging

In [28]:
gini["year"].unique()[:20]  # inspect unique year values

array([2000, 2008, 2018, 1996, 2002, 2005, 2012, 2014, 2015, 2016, 2017,
       2019, 2013, 1980, 1986, 1987, 1991, 1992, 1993, 1994])

In [29]:
gini["Gini"] = pd.to_numeric(gini["Gini"], errors="coerce") # make sure gini is numeric and consistent for merging

##### Keep only the variables needed for analysis

In [30]:
gini_use = gini[["Country", "year", "Gini"]].copy()

##### Handle and check missing values in key variables

In [31]:
gini_use = gini_use.dropna(subset=["Gini"])

##### Check cleaned Gini Index dataset

In [32]:
gini_use.head()
gini_use.info()
gini_use.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1896 entries, 0 to 1895
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  1896 non-null   object
 1   year     1896 non-null   int64
 2   Gini     1896 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 44.6+ KB

              year         Gini
count  1896.000000  1896.000000
mean   2006.275844    38.179325
std       9.348789     9.077638
min    1967.000000    20.200000
25%    2000.750000    31.200000
50%    2008.000000    36.100000
75%    2014.000000    44.100000
max    2021.000000    65.800000